# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9617cdf19f234db3006586c46c9f9c2b14382bd533667573c47b79e8bd1e13ce9e8ad0d0ba214223e93e0b385e50be3749a6723406b1fae6f20af8b69d52e1fd

test:
  secret_key_base: 5dc16b37238c9be583b40f12db8bd678e5a5d753a7943a8e18fc83dca6e76089c1b992a9a8b4713a35a2e427b661428c73621ce53ca34113b79175f92671052f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
